server:
  port: 8085

spring:
  application:
    name: karate-sandbox-api

logging:
  level:
    com.example.karate: INFO
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      enabled: true